### ISSUE TITLE
입력시 스크롤이 덜컹거림

### ISSUE THREAD

**Issue by jinwoo-kim-nhn** [dongwoo-kim/toast-ui-editor-qa#17]
* 입력시 스크롤이 살짝 덜컹거리는데, 기존 버전도 같은 현상이 보이지만 조금 더 심하게 느껴지네요. 일단 남겨봅니다
![testscroll](https://user-images.githubusercontent.com/35218826/76389037-c000ee80-63ad-11ea-9fd1-dcd7a1f2e37b.gif)

**Comment by jinwoo-kim-nhn** [comment]
2.0에서는 문제가 없네요 ㅎㅎ

**Comment by dongwoo-kim** [comment]
넵. 그럼 Close 하겠습니다.
