### ISSUE TITLE
인용문 스타일이 기존 버전과 다름

### ISSUE THREAD

**Issue by jinwoo-kim-nhn** [dongwoo-kim/toast-ui-editor-qa#18]
문제인지는 몰르겠지만 일단 올려봅니다.

## 뉴 버전
![스크린샷 2020-03-11 오후 3 05 01](https://user-images.githubusercontent.com/35218826/76389137-ee7ec980-63ad-11ea-904c-a06f46d97082.png)

## 기존버전
![스크린샷 2020-03-11 오후 3 05 04](https://user-images.githubusercontent.com/35218826/76389140-f0488d00-63ad-11ea-9f1f-212fd4cd323a.png)

**Comment by dongwoo-kim** [comment]
기존 버전은 두레이 스타일이라서.. 논이슈로 처리하겠습니다!
