### ISSUE TITLE
위지윅 에디터에서 문서 작성시 squire 콘솔 에러 로그 출력

### ISSUE THREAD

**Issue by js87zz** [dongwoo-kim/toast-ui-editor-qa#2]
<img width="497" alt="스크린샷 2020-03-10 오후 4 17 55" src="https://user-images.githubusercontent.com/37766175/76289895-8668ae80-62ed-11ea-9e26-7c34451aacc4.png">

**Comment by seonim-ryu** [comment]
제가합니다
