### ISSUE TITLE
WYSIWYG > 표 오른쪽 클릭 > 컨텍스트 메뉴가 이상한 위치에서 뜸

### ISSUE THREAD

**Issue by heenakwag** [dongwoo-kim/toast-ui-editor-qa#21]
## AS-IS
마우스 커서는 표 위에 있는데 컨텍스트 메뉴는 에디터 상단에 표시됨
![WYSIWYG_표_오른쪽클릭](https://user-images.githubusercontent.com/8615506/76491029-f7d06a80-646f-11ea-8c2c-bdf9ce2ed2d9.gif)

## TOBE
마우스 커서 옆에 컨텍스트 메뉴가 표시됨

**Comment by dongwoo-kim** [comment]
@seonim-ryu

**Comment by seonim-ryu** [comment]
* PR : https://github.com/nhn/tui.editor/pull/802
