### ISSUE TITLE
한글 title인 링크의 스타일이 파란색으로 표시됨(기존 붉은 색)

### ISSUE THREAD

**Issue by dongsik-yoo** [dongwoo-kim/toast-ui-editor-qa#22]
### 마크다운

```md
[아아](아아아)
[dkdk](dkdk)
```

### 2.0
![image](https://user-images.githubusercontent.com/26706716/76491265-a7a5d800-6470-11ea-982d-e0fe8d029b0e.png)

### 1.4.10
![image](https://user-images.githubusercontent.com/26706716/76491287-b12f4000-6470-11ea-84ed-e216a421a08b.png)

**Comment by seonim-ryu** [comment]
* PR : https://github.com/nhn/tui.editor/pull/804
