### ISSUE TITLE
부모 리스트를 숫자 리스트로 변경 시 자식 리스트의 변경

### ISSUE THREAD

**Issue by heenakwag** [dongwoo-kim/toast-ui-editor-qa#23]
## v1.4.10
![v1_숫자리스트로 변경](https://user-images.githubusercontent.com/8615506/76491528-4c281a00-6471-11ea-828e-d0959808a0cd.gif)

### 미리보기와 비교
![image](https://user-images.githubusercontent.com/8615506/76491688-ac1ec080-6471-11ea-98bf-84f9757a8ac4.png)

## v2.0.0
![v2_숫자리스트로 변경](https://user-images.githubusercontent.com/8615506/76491670-a2955880-6471-11ea-9a8e-a515f54fe59b.gif)

### 미리보기와 비교
![image](https://user-images.githubusercontent.com/8615506/76491744-c3f64480-6471-11ea-81bd-75f514c16caf.png)

어떤 것이 올바른 동작인지는 모르겠지만, 혹시 몰라서 이슈 등록합니다.
하지만 저는 v2.0 방식이 맞는 것 같아요. v1.4.10은 미리보기와 에디터의 내용이 다른데, v2.0에서는 동일하게 나와요.

**Comment by dongwoo-kim** [comment]
이건 오히려 개선된 포인트로 써먹으면 좋을 것 같네요 ㅎㅎ
@dotaitch 감사합니다!
