### ISSUE TITLE
차트의 레이블 높이가 너무 긺

### ISSUE THREAD

**Issue by heenakwag** [dongwoo-kim/toast-ui-editor-qa#29]
## ASIS
차트의 레이블 높이가 너무 긺
![image](https://user-images.githubusercontent.com/8615506/76493772-cad38600-6476-11ea-85a6-bb3ba7e2f682.png)

## TOBE
![image](https://user-images.githubusercontent.com/8615506/76493780-d2932a80-6476-11ea-85cc-74d7e558798c.png)

**Comment by seonim-ryu** [comment]
* PR : https://github.com/nhn/tui.editor/pull/813
