### ISSUE TITLE
위지윅 에디터에서 스크롤 위치에 따라 코드블럭 버튼 위치 계산 잘못되는 현상

### ISSUE THREAD

**Issue by js87zz** [dongwoo-kim/toast-ui-editor-qa#3]
<img width="1405" alt="스크린샷 2020-03-10 오후 4 12 32" src="https://user-images.githubusercontent.com/37766175/76290041-cb8ce080-62ed-11ea-8ca5-66fbbbb5cecb.png">

**Comment by seonim-ryu** [comment]
이것도 제가 합니다.
