### ISSUE TITLE
2줄에 걸친 셀렉션 후 bold 처리 시 표현되는 하이라이팅이 다름

### ISSUE THREAD

**Issue by junghwan-park** [dongwoo-kim/toast-ui-editor-qa#30]
## 2.0

![image](https://user-images.githubusercontent.com/7088720/76493918-20a82e00-6477-11ea-974a-e0d1d8c014f6.png)

## 1.4.10

![image](https://user-images.githubusercontent.com/7088720/76493928-27cf3c00-6477-11ea-919c-0e98b4a6019d.png)

**Comment by dongwoo-kim** [comment]
이건 CommonMark 스펙상 현재 구현이 맞는 거라서. 개선된 점으로 어필하겠습니다 ㅎㅎ
감사합니다.
