### ISSUE TITLE
리스트가 아닌 상태에서 개행해서 내용을 입력할 경우 미리보기 하이라이트가 개행 전 내용가지 하이라이트 됩니다. 

### ISSUE THREAD

**Issue by jungeun-cho** [dongwoo-kim/toast-ui-editor-qa#41]
질문) 문단 단위로 하이라이트 되어서 그런거죠?
![스크린샷 2020-04-23 14 26 30](https://user-images.githubusercontent.com/43128697/80063266-80aeeb80-8570-11ea-877b-6e61ae48de72.png)

**Comment by dongwoo-kim** [comment]
네. 이건 문단 단위라서 어쩔 수가 없네요 :( 
심각한 버그라고 느껴지지 않으면 그냥 스펙으로 봐야 할 것 같습니다.

**Comment by jungeun-cho** [comment]
넵!
