### ISSUE TITLE
숫자리스트에서 개행에도 리스트가 유지됩니다.

### ISSUE THREAD

**Issue by jung-han** [dongwoo-kim/toast-ui-editor-qa#42]
```
1. 가
2. 나
3. 다
4. 라
5. 마
6. 바
7. 사
8. 아
9. 자
10. 차
11. 카
12. 타
13. 파
14. 하


150. 오잉? 
151. 
```

## 2

![image](https://user-images.githubusercontent.com/35371660/80063564-219da680-8571-11ea-8479-f3ac159334c6.png)

## 1

![image](https://user-images.githubusercontent.com/35371660/80063581-2cf0d200-8571-11ea-945f-e8bb30a36edf.png)

**Comment by dongwoo-kim** [comment]
@jung-han 이건 마크다운 스펙이라. 논이슈 처리하겠습니다 :)
